#name: Build .NET 8 Console App on Tag
#
#on:
#  push:
#    tags:
#      - 'v*'
#
#jobs:
#  build-linux:
#    name: Build on Linux
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup .NET 8
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: '8.0.x'
#
#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Build for Linux x64
#        run: dotnet publish -c Release -r linux-x64 --self-contained true
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: linux-build
#          path: ./output/linux
#
#  build-windows:
#    name: Build on Windows
#    runs-on: windows-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup .NET 8
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: '8.0.x'
#
#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Build for Windows x64
#        run: dotnet publish -c Release -r win-x64 --self-contained true
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows-build
#          path: ./output/windows
#
